# Generated by Django 4.1.3 on 2022-12-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
